apiVersion: v1
kind: Namespace
metadata:
  name:  dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-permissions-dev
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: dev
rules:
- apiGroups: ["*"]
  resources: ["pods","deployments","replicasets"]
  verbs: ["get", "list", "watch"]

- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles"]
  verbs: ["get", "list", "watch"]



---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-pod-reader
  namespace: dev
subjects:
- kind: ServiceAccount
  name: demo-permissions-dev          # ahora coincide con el SA
  namespace: dev
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-busybox
  namespace: dev
  labels:
    app: my-busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-busybox
  template:
    metadata:
      labels:
        app: my-busybox
    spec:
      serviceAccountName: demo-permissions-dev   # coincide con el SA
      containers:
      - name: busybox
        image: bitnami/kubectl:1.27
        command: ["bash", "-c", "sleep 3600"]
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1024Mi"
