apiVersion: v1
kind: Namespace
metadata:
  name:  release
---

# file: role-view-apps.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-apps
  namespace: release          # <-- restringido al ns dev
rules:
- apiGroups: ["", "apps"]
  resources: ["pods", "deployments", "replicasets", "services", "configmaps"]
  verbs: ["get", "list", "watch"]

---
# file: rb-vaian-view.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vaian-view
  namespace: release
subjects:
- kind: User
  name: vaian                # <-- Debe coincidir con el CN / user del kubeconfig
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: view-apps
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-busybox-release
  namespace: release
  labels:
    app: my-busybox-release
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-busybox-release
  template:
    metadata:
      labels:
        app: my-busybox-release
    spec:
      containers:
      - name: busybox-release
        image: bitnami/kubectl:1.27
        command: ["bash", "-c", "sleep 3600"]
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1024Mi"
